### ISSUE TITLE
Buffer is undefined in some environments

### ISSUE THREAD

**Issue by frandiox** [LinusU/buffer-from#13]
@LinusU  Hi! I've found this package because it's used in `html-tokenize`, which is used in `@emotion/server`. This last package is related to server side rendering stuff and I'm trying to make it work in non-Node.js envrionments, such as Cloudflare Workers.

My problem is that this library (buffer-from) tries to access `Buffer` [on import](https://github.com/LinusU/buffer-from/blob/master/index.js#L6). Therefore, even if the rest of the functions are never called (they are not in this scenario), the app crashes due to having Buffer undefined.

Would you consider adding `typeof Buffer !== 'undefined' &&` in the logic for `isModern`?
Thanks!

**Comment by LinusU** [comment]
Hey,

This library isn't really needed anymore since all currently supported versions of Node.js supports the `Buffer.from` api natively. I would recommend sending a PR to `html-tokenize` that drops support for Node.js < 12 and drops this dependency at all.

That being said, I wouldn't mind publishing a patch version that adds the check you suggested, just to make it a bit easier for you. Could you double check that this commit https://github.com/LinusU/buffer-from/commit/570bcec008edca8233a5b921ec7c305a6c67398c works, and then I can publish a patch version 🚀

**Comment by frandiox** [comment]
@LinusU I see! Yes, that fixes it, thank you :)

**Comment by LinusU** [comment]
Published as [🚢 1.1.2 / 2021-07-29](https://github.com/LinusU/buffer-from/releases/tag/v1.1.2)

**Comment by frandiox** [comment]
@LinusU Thank you very much!
